### ISSUE TITLE
goleveldb: potential improvements

### ISSUE THREAD

**Issue by melekes** [cometbft/cometbft-db#102]
If `goleveldb` is picked as the primary DB for CometBFT, we should identify any potential improvements we can make.

- [defaults](https://github.com/syndtr/goleveldb/blob/master/leveldb/opt/options.go#L24)
- [Ethereum](https://github.com/ethereum/go-ethereum/blob/4d086430bd8c0b9549fde5259f74f6df6c96df65/ethdb/leveldb/leveldb.go)

## 1. Disable seek compaction

Multiple reports turning off seek compaction improves the compaction process:

https://github.com/google/leveldb/issues/857
https://github.com/klaytn/klaytn/pull/715
https://github.com/ethereum/go-ethereum/pull/20130

### 2. Pre-allocate memory for a batch

`goleveldb` could be more efficient when growing the batch buffer at once. It is better to pre-allocate the buffer.

### 3. Investigate changes made by Finschia team

https://github.com/Finschia/tm-db/commits/main

**Comment by faddat** [comment]
tbh everyone is moving to pebble

**Comment by melekes** [comment]
> tbh everyone is moving to pebble and goleveldb is no longer supported by its author and adds a replace statement to everything.

Thanks for the insight 👍 Who's moving to `pebble`? Please comment on https://github.com/cometbft/cometbft/issues/1039, which is more relevant to this discussion.

**Comment by faddat** [comment]
I thought that geth recently announced a move to pebble?

What you're saying here makes it seem maybe not though
