### ISSUE TITLE
Q: Does anyone use databases other than goleveldb or rocksdb?

### ISSUE THREAD

**Issue by faddat** [cometbft/cometbft-db#117]
Only rocks out of these 4 works in prod but when you use rocks in prod, if the chain uses cosmwasm, there's way too much overhead due to more cgo than any computer can reasonably tolerate.

**Comment by faddat** [comment]
Anyone have proof that these work in production?

* cleveldb (it might)

afaik, 

* bolt literally doesn't work in prod
* badger literally doesn't work in prod

both are too slow to sync with

**Comment by melekes** [comment]
linking https://github.com/cometbft/cometbft/issues/1039 here as well

**Comment by faddat** [comment]
* https://github.com/tendermint/tendermint/pull/9742

did it a long time ago

**Comment by faddat** [comment]
Resolved in #135

**Comment by adizere** [comment]
Closing in favor of #143
