### ISSUE TITLE
Mark cleveldb and bolt as deprecated

### ISSUE THREAD

**Issue by adizere** [cometbft/cometbft-db#143]
Supersedes #117 and #135

**Comment by andynog** [comment]
I think it's important to provide operators with documentation and scripts when they have to migrate from a deprecated database. 

But more importantly, we need to ensure that DB migration paths exist and work; I wonder if we can test that. For example, once a DB is deprecated (e.g., Badger), and the operator moves to another DB (e.g., Pebble), do we currently have a way to test the migration?

The abstraction of cometbft-db over DBs should guarantee these migration paths. Still, I don't know if any implementation details over these abstractions would make the possibility of a migration path untrue. We can only provide these guarantees by testing a migration path (e.g., via a script).
