### ISSUE TITLE
Make a second DB "IterKey" API that returns a key to the caller that can potentially mutate

### ISSUE THREAD

**Issue by ValarDragon** [cometbft/cometbft-db#156]
Currently the Iterator.Key() API makes a copy of the key it gets from the database. This is because the database's iterator returns something it will mutate on the subsequent .Next() call for heap efficiency. This extra copy causes very large heap allocation (and time overheads) to query serving nodes, and a 1% time overhead to the entire state machine time for Osmosis.

On a heap allocation profile of a query serving Osmosis RPC node over an hour, it has 450 gigabytes allocated from this API. On spot-check, none of the big ones need this copying behavior. (160GB removed from a tendermint update, but the remaining 290GB are still from this API)

![image](https://github.com/cometbft/cometbft-db/assets/6440154/19f42104-7cbd-4d93-bcae-56c7a14cf421)

In the state machine, we see 1% of state machine execution time is blocked on copying this key, again in situations where I don't think we need any of this either. 
![image](https://github.com/cometbft/cometbft-db/assets/6440154/d4ec4018-1ec3-4763-ab4e-f471ee12bbb0)

-------------

Proposal: Add a new method `KeyMut()` to the interface for Iterator. The caller should not mutate this key, and the expectation is that the key may get mutated on the next `.Next()` call. 

I'm not stoked about the naming of this method, so happy for better ideas

**Comment by melekes** [comment]
Do we even modify the key in CometBFT? Because the contract says `CONTRACT: readonly []byte`
