### ISSUE TITLE
ci: Intermittent test failures

### ISSUE THREAD

**Issue by thanethomson** [cometbft/cometbft-db#23]
I've been seeing the occasional test failure here in CI, like [this one](https://github.com/cometbft/cometbft-db/actions/runs/3934156405/jobs/6728617699), where I see the following output:

```
signal: illegal instruction (core dumped)
```

It's unclear whether this is a problem in our code, or in a linked library.

I have not yet managed to reproduce this locally though. When testing locally with the Docker image, it always passes for me.

**Comment by melekes** [comment]
Not seeing this anymore.
