### ISSUE TITLE
Unify behaviour of `Get` when key is not in DB

### ISSUE THREAD

**Issue by jmalicevic** [cometbft/cometbft-db#81]
Currently, when calling `Get` for a key that does not exist is not treated the same accross all DB backends. For GolevelDB, the error is checked and if it is `ErrNotFound` , cometbft-db returns no error. For RocksDB for example cometbft-db just forwards the error returned by the DB backend. 

We need to unify this behaviour accross the different databases.

**Comment by faddat** [comment]
nah, we need to rip out pointless databases (imo)

**Comment by melekes** [comment]
Marking this as `wontfix` because of https://github.com/cometbft/cometbft/issues/1039

**Comment by faddat** [comment]
easily fixed by not using rocks, bolt, cleveldb and badgerdb
